In [169]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib notebook

In [3]:
imdb_title_basics = pd.read_csv('./data/imdb.title.basics.csv.gz')

In [4]:
imdb_title_ratings = pd.read_csv('./data/imdb.title.ratings.csv.gz')

In [9]:
imdb_title_basics.genres.value_counts()

Documentary                      32185
Drama                            21486
Comedy                            9177
Horror                            4372
Comedy,Drama                      3519
Thriller                          3046
Action                            2219
Biography,Documentary             2115
Drama,Romance                     2079
Comedy,Drama,Romance              1558
Documentary,Drama                 1554
Comedy,Romance                    1507
Romance                           1454
Documentary,Music                 1365
Drama,Thriller                    1335
Documentary,History               1289
Horror,Thriller                   1253
Biography,Documentary,History     1230
Biography,Documentary,Drama       1028
Family                             939
Animation                          828
Drama,Family                       784
Action,Crime,Drama                 727
Comedy,Horror                      724
Crime,Drama                        723
Crime                              720
Sci-Fi                             712
Music                              701
Documentary,Sport                  669
Crime,Drama,Thriller               665
                                 ...
Animation,Horror,Romance             1
Fantasy,Music,Sci-Fi                 1
Comedy,Documentary,Western           1
Adventure,Comedy,Reality-TV          1
Action,Musical,Thriller              1
Adventure,History,War                1
Animation,Crime,Thriller             1
Adventure,History,Western            1
Animation,Documentary,Mystery        1
Music,Musical,Romance                1
History,News,War                     1
Action,Family,Western                1
Fantasy,War                          1
Action,Animation,War                 1
Documentary,Music,Western            1
Crime,Music                          1
History,Mystery                      1
Family,Romance,Sport                 1
Family,News                          1
Family,Horror                        1
Action,Sport,Thriller                1
History,Musical,Romance              1
Family,Fantasy,Western               1
Biography,Family,Mystery             1
Animation,Biography,Fantasy          1
Crime,Western                        1
Comedy,History,Mystery               1
Comedy,History,Sport                 1
Fantasy,History,Horror               1
Drama,Family,Short                   1
Name: genres, Length: 1085, dtype: int64

In [12]:
imdb_title_basics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146144 entries, 0 to 146143
Data columns (total 6 columns):
tconst             146144 non-null object
primary_title      146144 non-null object
original_title     146123 non-null object
start_year         146144 non-null int64
runtime_minutes    114405 non-null float64
genres             140736 non-null object
dtypes: float64(1), int64(1), object(4)
memory usage: 6.7+ MB

In [11]:
imdb_title_basics.loc[imdb_title_basics.genres == 'Family,Horror']

,tconst,primary_title,original_title,start_year,runtime_minutes,genres
139070,tt8979234,No Exit,No Exit,2018,70.0,"Family,Horror"

In [20]:
imdb_title_ratings.head()

       tconst  averagerating  numvotes
0  tt10356526            8.3        31
1  tt10384606            8.9       559
2   tt1042974            6.4        20
3   tt1043726            4.2     50352
4   tt1060240            6.5        21

In [26]:
imdb_basics_rating = pd.merge(imdb_title_basics, imdb_title_ratings, on=['tconst'], how='outer', indicator=True)

In [27]:
imdb_basics_rating.head()

,tconst,primary_title,original_title,start_year,runtime_minutes,genres,averagerating,numvotes,_merge
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama",7.0,77.0,both
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama",7.2,43.0,both
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama,6.9,4517.0,both
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama",6.1,13.0,both
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy",6.5,119.0,both

In [31]:
imdb_basics_rating.averagerating.isna().sum()

72288

In [32]:
imdb_title_principals = pd.read_csv('./data/imdb.title.principals.csv.gz')

In [33]:
imdb_title_principals.head()

      tconst  ordering     nconst  category       job        characters
0  tt0111414         1  nm0246005     actor       NaN       ["The Man"]
1  tt0111414         2  nm0398271  director       NaN               NaN
2  tt0111414         3  nm3739909  producer  producer               NaN
3  tt0323808        10  nm0059247    editor       NaN               NaN
4  tt0323808         1  nm3579312   actress       NaN  ["Beth Boothby"]

In [34]:
imdb_title_principals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028186 entries, 0 to 1028185
Data columns (total 6 columns):
tconst        1028186 non-null object
ordering      1028186 non-null int64
nconst        1028186 non-null object
category      1028186 non-null object
job           177684 non-null object
characters    393360 non-null object
dtypes: int64(1), object(5)
memory usage: 47.1+ MB

In [36]:
imdb_title_principals.loc[imdb_title_principals.category == 'director']

             tconst  ordering      nconst  category  job characters
1         tt0111414         2   nm0398271  director  NaN        NaN
8         tt0323808         5   nm0362736  director  NaN        NaN
18        tt0417610         5   nm1145057  director  NaN        NaN
28        tt0469152         5   nm0707738  director  NaN        NaN
35        tt0473032         3   nm0776090  director  NaN        NaN
41        tt0475290         5   nm0001053  director  NaN        NaN
42        tt0475290         6   nm0001054  director  NaN        NaN
51        tt0477302         5   nm0197636  director  NaN        NaN
61        tt0780548         5   nm0007082  director  NaN        NaN
71        tt0879405         5   nm1275939  director  NaN        NaN
81        tt0884726         5   nm0278181  director  NaN        NaN
82        tt0884726         6   nm0820800  director  NaN        NaN
91        tt0972848         5   nm2568212  director  NaN        NaN
101      tt10011682         5   nm0907867  director  NaN        NaN
110      tt10014042         5  nm10544448  director  NaN        NaN
118      tt10017454         5   nm0052024  director  NaN        NaN
138      tt10022952         5   nm4084207  director  NaN        NaN
148      tt10039344         5   nm2280148  director  NaN        NaN
153      tt10045136         1   nm4963380  director  NaN        NaN
162      tt10047128         5   nm4597102  director  NaN        NaN
171      tt10050612         5   nm2259048  director  NaN        NaN
173      tt10054536         2  nm10561671  director  NaN        NaN
177      tt10108062         3   nm8742444  director  NaN        NaN
180      tt10109836         1   nm2159386  director  NaN        NaN
185      tt10110794         5   nm0720109  director  NaN        NaN
194      tt10121022         5   nm7742644  director  NaN        NaN
204      tt10122042         5  nm10592286  director  NaN        NaN
212      tt10133066         4   nm3481271  director  NaN        NaN
219      tt10147214         5   nm6301348  director  NaN        NaN
231      tt10151838         4   nm3907861  director  NaN        NaN
...             ...       ...         ...       ...  ...        ...
1027986   tt9529656         5   nm0793642  director  NaN        NaN
1027996   tt9537936         5  nm10370143  director  NaN        NaN
1028002   tt9549028         2  nm10375424  director  NaN        NaN
1028003   tt9549028         3  nm10375423  director  NaN        NaN
1028004   tt9549028         4   nm8533630  director  NaN        NaN
1028005   tt9549028         5   nm8533565  director  NaN        NaN
1028012   tt9555284         5   nm3859440  director  NaN        NaN
1028022   tt9557092         5   nm8968432  director  NaN        NaN
1028029   tt9557190         3   nm1048560  director  NaN        NaN
1028037   tt9564448         4   nm1977735  director  NaN        NaN
1028047   tt9573058         5  nm10366114  director  NaN        NaN
1028062   tt9577520         1   nm5675408  director  NaN        NaN
1028073   tt9581172         5   nm0911017  director  NaN        NaN
1028080   tt9581844         5   nm2285610  director  NaN        NaN
1028090   tt9581996         5   nm0246360  director  NaN        NaN
1028091   tt9581996         6   nm0611275  director  NaN        NaN
1028101   tt9592190         5   nm7006696  director  NaN        NaN
1028102   tt9592190         6   nm3951087  director  NaN        NaN
1028111   tt9658966         3   nm1714943  director  NaN        NaN
1028116   tt9662266         5   nm8997079  director  NaN        NaN
1028126   tt9670776         5   nm2277447  director  NaN        NaN
1028136   tt9670894         5   nm7840985  director  NaN        NaN
1028137   tt9670894         6   nm4039933  director  NaN        NaN
1028146   tt9672244         5   nm0261685  director  NaN        NaN
1028154   tt9673560         4   nm3698251  director  NaN        NaN
1028165   tt9679036         5   nm9728620  director  NaN        NaN
1028171   tt9681728         5  nm10436661  director  NaN        NaN
1028179   tt9689618         4   nm9652770  director  NaN        NaN
1028180   tt9689618         5  nm10439725  director  NaN        NaN
1028183   tt9692684         3  nm10441594  director  NaN        NaN

[146393 rows x 6 columns]

In [49]:
tn_movie_budgets = pd.read_csv('./data/tn.movie_budgets.csv.gz')

In [50]:
tn_movie_budgets.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"

In [52]:
tn_movie_budgets.release_date = pd.to_datetime(tn_movie_budgets.release_date)

In [54]:
tn_movie_budgets['release_year'] = tn_movie_budgets.release_date.dt.year

In [73]:
tn_movie_budgets.loc[:, 'production_budget':'worldwide_gross'] = \
    tn_movie_budgets.loc[:, 'production_budget':'worldwide_gross'].replace('[^.0-9]', '', regex=True).astype(int)

In [141]:
tn_movie_budgets['dom_roi'] = (((tn_movie_budgets.domestic_gross - tn_movie_budgets.production_budget) / tn_movie_budgets.production_budget) * 100).astype(int)

In [142]:
tn_movie_budgets['world_roi'] = (((tn_movie_budgets.worldwide_gross - tn_movie_budgets.production_budget) / tn_movie_budgets.production_budget) * 100).astype(int)

In [103]:
tn_movie_budgets.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,release_year,dom_roi,world_roi
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009,178.94,653.26
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,58.71,254.67
2,3,2019-06-07,Dark Phoenix,350000000,42762350,149762350,2019,12.22,42.79
3,4,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,138.84,424.38
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,195.64,415.37

In [98]:
#James Cameron not found b/c imdb is 2010+. Avatar is 2009.  Would need to pull older data.
imdb_basics_rating[imdb_basics_rating.primary_title == 'Avatar']

,tconst,primary_title,original_title,start_year,runtime_minutes,genres,averagerating,numvotes,_merge
17060,tt1775309,Avatar,Abatâ,2011,93.0,Horror,6.1,43.0,both

In [126]:
#join imdb with tn
imdb_tn_primary_title = pd.merge(
    imdb_basics_rating, 
    tn_movie_budgets,
    left_on=['primary_title', 'start_year'],
    right_on=['movie', 'release_year'],
    how='inner',
)

In [125]:
imdb_tn_original_title = pd.merge(
    imdb_basics_rating, 
    tn_movie_budgets,
    left_on=['original_title', 'start_year'],
    right_on=['movie', 'release_year'],
    how='inner',
)

In [128]:
imdb_tn_all = pd.concat([imdb_tn_primary_title, imdb_tn_original_title])

In [131]:
imdb_tn_all.drop_duplicates(inplace=True)

In [166]:
imdb_tn_all['main_genre'] = imdb_tn_all.genres.str.split(',', expand=True)[0].astype('category')

In [172]:
imdb_tn_all.main_genre.unique()

[Action, Adventure, Comedy, Horror, Drama, ..., Romance, Sci-Fi, Family, Music, Western]
Length: 19
Categories (18, object): [Action, Adventure, Comedy, Horror, ..., Sci-Fi, Family, Music, Western]

In [195]:
imdb_tn_all.groupby('main_genre')[['domestic_gross', 'production_budget']].corr().iloc[0::2,-1]

main_genre
Action       domestic_gross    0.685936
Adventure    domestic_gross    0.699237
Animation    domestic_gross    0.887586
Biography    domestic_gross    0.616357
Comedy       domestic_gross    0.580697
Crime        domestic_gross    0.668026
Documentary  domestic_gross    0.740886
Drama        domestic_gross    0.588137
Family       domestic_gross    0.991303
Fantasy      domestic_gross    0.972378
Horror       domestic_gross    0.435556
Music        domestic_gross         NaN
Musical      domestic_gross         NaN
Mystery      domestic_gross    0.911450
Romance      domestic_gross    0.999958
Sci-Fi       domestic_gross    1.000000
Thriller     domestic_gross    0.923102
Western      domestic_gross         NaN
Name: production_budget, dtype: float64

In [222]:
genre_dom_gross_corr_prod_budget = imdb_tn_all.groupby('main_genre')[['domestic_gross', 'production_budget']].corr()

In [226]:
genre_dom_gross_corr_prod_budgest = genre_dom_gross_corr_prod_budget.iloc[::2, -1].reset_index()

In [230]:
genre_dom_gross_corr_prod_budget.drop(columns='level_1', inplace=True)

In [234]:
genre_dom_gross_corr_prod_budget.rename(columns={'production_budget': 'prod_dom_gross_corr'}, inplace=True)

In [235]:
#Low budget with high domestic gross
genre_dom_gross_corr_prod_budget.sort_values(by='prod_dom_gross_corr')

     main_genre  prod_dom_gross_corr
10       Horror             0.435556
4        Comedy             0.580697
7         Drama             0.588137
3     Biography             0.616357
5         Crime             0.668026
0        Action             0.685936
1     Adventure             0.699237
6   Documentary             0.740886
2     Animation             0.887586
13      Mystery             0.911450
16     Thriller             0.923102
9       Fantasy             0.972378
8        Family             0.991303
14      Romance             0.999958
15       Sci-Fi             1.000000
11        Music                  NaN
12      Musical                  NaN
17      Western                  NaN

In [243]:
sns.pairplot(
    x_vars=['production_budget'], 
    y_vars=['domestic_gross'], 
    data=imdb_tn_all.loc[imdb_tn_all.main_genre == 'Horror'],
    height=5,
    #hue='main_genre',
);

In [255]:
#imdb_tn_all.to_pickle('../processed_data/imdb_tn_genres_revenues.pkl')